# -*- coding: utf-8 -*-
"""task_datascience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MI6Cys5wc4dUgc4-0_AI8UoxzyyvTElu
"""

from google.colab import files
uploaded =files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

df = pd.read_csv('Ice Cream.csv')

print("First 5 rows:\n", df.head())

print("\nDisplay statistics:\n", df.describe())

print("\nMissing values:\n", df.isnull().sum())

df.dropna(inplace=True)

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Temperature', y='Revenue', data=df)
plt.title('Temperature vs Ice Sales Revenue')
plt.xlabel('Temperature (°C)')
plt.ylabel('Revenue (USD)')
plt.show()

X = df[['Temperature']]
y = df['Revenue']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

rmse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nModel Evaluation:")
print(f"RMSE: {rmse:.2f}")
print(f"MAE: {mae:.2f}")
print(f"R² Score: {r2:.2f}")

plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_test['Temperature'], y=y_test, label='Actual')
sns.scatterplot(x=X_test['Temperature'], y=y_pred, label='Predicted')
plt.title('Actual vs Predicted Revenue')
plt.show()

plt.figure(figsize=(8, 6))
correlation = df.corr(numeric_only=True)
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

results = pd.DataFrame({'Actual': y_test.values, 'Predicted': y_pred})
print(results.head(10))

